// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package inject

import (
	"context"
	"github.com/LyricTian/gin-admin/v9/internal/module/rbac"
	"github.com/LyricTian/gin-admin/v9/internal/module/rbac/api"
	"github.com/LyricTian/gin-admin/v9/internal/module/rbac/biz"
	"github.com/LyricTian/gin-admin/v9/internal/module/rbac/dao"
	"github.com/LyricTian/gin-admin/v9/internal/x/utilx"
)

// Injectors from wire.go:

func BuildInjector(ctx context.Context) (*Injector, func(), error) {
	auther, cleanup, err := InitAuth(ctx)
	if err != nil {
		return nil, nil, err
	}
	cacher, cleanup2, err := InitCache(ctx)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	db, cleanup3, err := InitDB(ctx)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	roleRepo := &dao.RoleRepo{
		DB: db,
	}
	menuActionResourceRepo := &dao.MenuActionResourceRepo{
		DB: db,
	}
	casbinx := &rbac.Casbinx{
		Cache:                  cacher,
		RoleRepo:               roleRepo,
		MenuActionResourceRepo: menuActionResourceRepo,
	}
	transRepo := utilx.TransRepo{
		DB: db,
	}
	menuRepo := dao.MenuRepo{
		DB: db,
	}
	menuActionRepo := dao.MenuActionRepo{
		DB: db,
	}
	daoMenuActionResourceRepo := dao.MenuActionResourceRepo{
		DB: db,
	}
	menuBiz := &biz.MenuBiz{
		TransRepo:              transRepo,
		MenuRepo:               menuRepo,
		MenuActionRepo:         menuActionRepo,
		MenuActionResourceRepo: daoMenuActionResourceRepo,
	}
	userRepo := dao.UserRepo{
		DB: db,
	}
	userRoleRepo := dao.UserRoleRepo{
		DB: db,
	}
	daoRoleRepo := dao.RoleRepo{
		DB: db,
	}
	userBiz := &biz.UserBiz{
		TransRepo:    transRepo,
		UserRepo:     userRepo,
		UserRoleRepo: userRoleRepo,
		RoleRepo:     daoRoleRepo,
		Cache:        cacher,
	}
	menuAPI := &api.MenuAPI{
		MenuBiz: menuBiz,
	}
	roleMenuRepo := dao.RoleMenuRepo{
		DB: db,
	}
	roleBiz := &biz.RoleBiz{
		TransRepo:    transRepo,
		RoleRepo:     daoRoleRepo,
		RoleMenuRepo: roleMenuRepo,
		UserRoleRepo: userRoleRepo,
		Cache:        cacher,
	}
	roleAPI := &api.RoleAPI{
		RoleBiz: roleBiz,
	}
	userAPI := &api.UserAPI{
		UserBiz: userBiz,
	}
	daoUserRepo := &dao.UserRepo{
		DB: db,
	}
	daoUserRoleRepo := &dao.UserRoleRepo{
		DB: db,
	}
	daoMenuRepo := &dao.MenuRepo{
		DB: db,
	}
	daoMenuActionRepo := &dao.MenuActionRepo{
		DB: db,
	}
	loginBiz := &biz.LoginBiz{
		Auth:           auther,
		Cache:          cacher,
		UserRepo:       daoUserRepo,
		UserRoleRepo:   daoUserRoleRepo,
		RoleRepo:       roleRepo,
		MenuRepo:       daoMenuRepo,
		MenuActionRepo: daoMenuActionRepo,
	}
	loginAPI := &api.LoginAPI{
		LoginBiz: loginBiz,
	}
	rbacRBAC := &rbac.RBAC{
		DB:       db,
		Casbinx:  casbinx,
		MenuBiz:  menuBiz,
		UserBiz:  userBiz,
		MenuAPI:  menuAPI,
		RoleAPI:  roleAPI,
		UserAPI:  userAPI,
		LoginAPI: loginAPI,
	}
	injector := &Injector{
		Auth:  auther,
		Cache: cacher,
		DB:    db,
		RBAC:  rbacRBAC,
	}
	return injector, func() {
		cleanup3()
		cleanup2()
		cleanup()
	}, nil
}
